import Head from "next/head";
import axios from "axios";
import React, { useState } from "react";
import BsSearch from "react-icons/bs";
import MainSection from "@/components/Main";
import SideBox from "@/components/SideBox";

export default function Home() {
  const [city, setCity] = useState("warsaw");
  const [weather, setWeather] = useState(undefined);
  const [loading, setLoading] = useState(false);

  const getWeather = (input) => {
    console.log(input);
    let url = `https://api.openweathermap.org/data/2.5/weather?q=${input}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
    setLoading(true);
    axios.get(url).then((res) => {
      setWeather(res.data);
      console.log(res.data);
    });
    setCity("");
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col-reverse sm:flex-row">
        <MainSection weather={weather}></MainSection>
        <SideBox weather={weather} fetchFunction={getWeather}></SideBox>
      </div>
    </>
  );
}
